import './css/style.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/footer'
import NavBar from '@/components/nav/nav-bar'
import { SessionProvider } from '@/context/SessionContext'
import { AOSInit } from './_components/aos-init'
import ShoppingCart from './_components/shopping-cart/shopping-cart'
import { CartProvider } from '@/context/CartContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <AOSInit />
            <body className={inter.className}>
                <SessionProvider>
                    <CartProvider>
                        <div className="flex min-h-screen flex-col">
                            <ShoppingCart />
                            <NavBar />
                            <div className="flex-grow">{children}</div>
                            <Footer />
                        </div>
                    </CartProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
