import './css/style.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/footer'
import NavBar from '@/components/nav/nav-bar'
import { LotteryProvider } from '@/context/LotteryContext'
import { SessionProvider } from '@/context/SessionContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider>
                    <LotteryProvider>
                        <div className="flex min-h-screen flex-col">
                            <NavBar />
                            <div className="flex-grow">{children}</div>
                            <Footer />
                        </div>
                    </LotteryProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
